# Generated by Django 5.1.9 on 2026-08-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kaizens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KaizenClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closure_date', models.DateTimeField()),
                ('closure_remarks', models.TextField(blank=True)),
                ('all_actions_completed', models.BooleanField(default=False)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kaizens_closed', to=settings.AUTH_USER_MODEL)),
                ('kaizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure', to='kaizens.kaizen')),
            ],
            options={
                'verbose_name': 'Kaizen Closure',
                'verbose_name_plural': 'Kaizen Closures',
                'db_table': 'kaizen_closures',
            },
        ),
        migrations.CreateModel(
            name='KaizenVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementation_verified', models.BooleanField(default=False)),
                ('evidence_verified', models.BooleanField(default=False)),
                ('result_verified', models.BooleanField(default=False)),
                ('benefits_verified', models.BooleanField(default=False)),
                ('cost_savings_verified', models.BooleanField(default=False)),
                ('impact_actions_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_remarks', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Overall verification status')),
                ('kaizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='kaizens.kaizen')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kaizen_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kaizen Verification',
                'verbose_name_plural': 'Kaizen Verifications',
                'db_table': 'kaizen_verifications',
            },
        ),
    ]
