# Generated by Django 5.1.9 on 2026-08-16 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizens', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CftMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(default='CFT Reviewer', max_length=120)),
                ('department', models.CharField(choices=[('Operations', 'Operations'), ('Quality', 'Quality'), ('Engineering', 'Engineering'), ('Maintenance', 'Maintenance'), ('Machining', 'Machining'), ('Management', 'Management'), ('Other', 'Other')], default='Operations', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cft_members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('opened_by_name', models.CharField(default='Committee Lead', max_length=120)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('present_member_ids', models.TextField(blank=True, default='', help_text='Comma-separated list of CftMember IDs who are present')),
                ('category_overrides', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'cft_sessions',
                'ordering': ['-year', '-opened_at'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CftStarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(help_text='Star rating: 1 (lowest) to 5 (highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rated_at', models.DateTimeField(auto_now=True)),
                ('kaizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cft_star_ratings', to='kaizens.kaizen')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_ratings', to='voting.cftmember')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_ratings', to='voting.cftsession')),
            ],
            options={
                'db_table': 'cft_star_ratings',
                'ordering': ['-stars'],
                'unique_together': {('session', 'member', 'kaizen')},
            },
        ),
    ]
