# Generated by Django 5.1.9 on 2026-08-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizen',
            name='impact_assessment_data',
            field=models.JSONField(blank=True, default=None, help_text='5M, Safety, PFD, PFMEA impact assessment data from committee review', null=True),
        ),
    ]
