# Generated by Django 5.1.9 on 2026-08-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kaizens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('rework', 'Rework'), ('classify', 'Classify'), ('impact_review', 'Impact Review'), ('action_assign', 'Action Assignment'), ('action_update', 'Action Update'), ('action_complete', 'Action Completion'), ('verify', 'Verify'), ('vote', 'Vote'), ('close', 'Close'), ('evidence_upload', 'Evidence Upload'), ('evidence_delete', 'Evidence Delete'), ('resource_allocate', 'Resource Allocate'), ('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('previous_value', models.TextField(blank=True, help_text='JSON snapshot of previous state')),
                ('new_value', models.TextField(blank=True, help_text='JSON snapshot of new state')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('remarks', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('kaizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='kaizens.kaizen')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'managed': True,
                'indexes': [models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['kaizen'], name='audit_logs_kaizen__18b5e3_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx')],
            },
        ),
    ]
