# Generated by Django 5.1.9 on 2026-08-13 18:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kaizens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Month name (e.g., July)', max_length=20)),
                ('year', models.IntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('eligible_kaizens', models.ManyToManyField(blank=True, related_name='voting_sessions', to='kaizens.kaizen')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voting_sessions_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kaizen_voting_sessions',
                'ordering': ['-year', '-opened_at'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CftVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='Rank: 1 = Best, 2 = Second, 3 = Third', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('kaizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cft_votes', to='kaizens.kaizen')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cft_votes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.votingsession')),
            ],
            options={
                'db_table': 'kaizen_votes',
                'ordering': ['rank'],
                'unique_together': {('session', 'voter', 'kaizen')},
            },
        ),
    ]
