# Generated by Django 5.1.9 on 2026-08-13 18:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(db_index=True, help_text='Auto-generated serial number (e.g., KZ-2026-001)', max_length=20, unique=True)),
                ('month', models.CharField(help_text='Month name (e.g., June, July)', max_length=20)),
                ('suggestion_date', models.DateField(help_text='Date the suggestion was made')),
                ('title', models.CharField(help_text='Kaizen improvement title', max_length=500)),
                ('problem_before', models.TextField(help_text='Description of the problem before improvement')),
                ('counter_measure_after', models.TextField(help_text='Description of the countermeasure / improvement after')),
                ('area', models.CharField(help_text='Plant area', max_length=200)),
                ('mini_factory', models.CharField(help_text='Mini-factory designation', max_length=100)),
                ('location', models.CharField(help_text='Specific location', max_length=200)),
                ('machine', models.CharField(blank=True, help_text='Machine/equipment name', max_length=200)),
                ('closing_target_date', models.DateField(blank=True, help_text='Target date for closing', null=True)),
                ('implementation_date', models.DateField(blank=True, help_text='Actual implementation date', null=True)),
                ('cost_save', models.DecimalField(decimal_places=2, default=0, help_text='Cost saving in INR', max_digits=15)),
                ('idea_by', models.CharField(help_text='Name of the person who suggested the idea', max_length=200)),
                ('implemented_by', models.CharField(blank=True, help_text='Person/team who implemented', max_length=200)),
                ('prepared_by', models.CharField(blank=True, help_text='Person who prepared the Kaizen sheet', max_length=200)),
                ('approved_by', models.CharField(blank=True, help_text='Approver name', max_length=200)),
                ('verified_by_name', models.CharField(blank=True, help_text='Verifier name', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('good_point', 'Good Point'), ('rejected', 'Rejected'), ('rework', 'Returned for Rework'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('classification', models.CharField(choices=[('kaizen', 'Kaizen'), ('good_point', 'Good Point'), ('pending', 'Pending'), ('none', 'None')], default='pending', max_length=20)),
                ('remark', models.TextField(blank=True, help_text='Reviewer/manager remarks')),
                ('result', models.TextField(blank=True, help_text='Result description after implementation')),
                ('photo_before', models.ImageField(blank=True, help_text='Before improvement photo', null=True, upload_to='kaizen_photos/before/')),
                ('photo_after', models.ImageField(blank=True, help_text='After improvement photo', null=True, upload_to='kaizen_photos/after/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_reviewer', models.ForeignKey(blank=True, help_text='Reviewer assigned to this Kaizen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaizens_to_review', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this Kaizen', on_delete=django.db.models.deletion.PROTECT, related_name='kaizens_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kaizen',
                'verbose_name_plural': 'Kaizens',
                'db_table': 'kaizens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KaizenBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productivity', models.BooleanField(default=False, help_text='P - Productivity improvement')),
                ('quality', models.BooleanField(default=False, help_text='Q - Quality improvement')),
                ('cost', models.BooleanField(default=False, help_text='C - Cost reduction')),
                ('delivery', models.BooleanField(default=False, help_text='D - Delivery improvement')),
                ('safety', models.BooleanField(default=False, help_text='S - Safety improvement')),
                ('morale', models.BooleanField(default=False, help_text='M - Morale improvement')),
                ('kaizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='kaizens.kaizen')),
            ],
            options={
                'verbose_name': 'Kaizen Benefit',
                'verbose_name_plural': 'Kaizen Benefits',
                'db_table': 'kaizen_benefits',
            },
        ),
        migrations.CreateModel(
            name='KaizenCostSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_inr', models.DecimalField(decimal_places=2, default=0, help_text='Total savings in INR', max_digits=15)),
                ('monthly_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly recurring savings in INR', max_digits=15, null=True)),
                ('annual_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Annual savings in INR', max_digits=15, null=True)),
                ('calculation_notes', models.TextField(blank=True, help_text='Notes on how savings were calculated')),
                ('kaizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_saving_detail', to='kaizens.kaizen')),
            ],
            options={
                'verbose_name': 'Kaizen Cost Saving',
                'verbose_name_plural': 'Kaizen Cost Savings',
                'db_table': 'kaizen_cost_savings',
            },
        ),
        migrations.CreateModel(
            name='KaizenEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=10)),
                ('file', models.ImageField(upload_to='kaizen_evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kaizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='kaizens.kaizen')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kaizen Evidence',
                'verbose_name_plural': 'Kaizen Evidence',
                'db_table': 'kaizen_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kaizen',
            index=models.Index(fields=['status'], name='kaizens_status_499ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='kaizen',
            index=models.Index(fields=['classification'], name='kaizens_classif_b2794d_idx'),
        ),
        migrations.AddIndex(
            model_name='kaizen',
            index=models.Index(fields=['area'], name='kaizens_area_de3e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='kaizen',
            index=models.Index(fields=['mini_factory'], name='kaizens_mini_fa_00574d_idx'),
        ),
        migrations.AddIndex(
            model_name='kaizen',
            index=models.Index(fields=['month'], name='kaizens_month_a022b9_idx'),
        ),
        migrations.AddIndex(
            model_name='kaizen',
            index=models.Index(fields=['created_by'], name='kaizens_created_7bee11_idx'),
        ),
        migrations.AddIndex(
            model_name='kaizen',
            index=models.Index(fields=['assigned_reviewer'], name='kaizens_assigne_c9d035_idx'),
        ),
        migrations.AddIndex(
            model_name='kaizen',
            index=models.Index(fields=['-created_at'], name='kaizens_created_6d90f5_idx'),
        ),
    ]
