# Generated by Django 5.1.9 on 2026-08-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaizens', '0002_add_impact_assessment_data_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaizen',
            name='impact_assessment_data',
        ),
    ]
