# Generated by Django 5.1.9 on 2026-08-19 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizens', '0003_remove_kaizen_impact_assessment_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaizen',
            name='approved_by',
            field=models.CharField(blank=True, default='', help_text='Approver name', max_length=200),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='area',
            field=models.CharField(blank=True, default='', help_text='Plant area', max_length=200),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='counter_measure_after',
            field=models.TextField(blank=True, default='', help_text='Description of the countermeasure / improvement after'),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='idea_by',
            field=models.CharField(blank=True, default='', help_text='Name of the person who suggested the idea', max_length=200),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='implemented_by',
            field=models.CharField(blank=True, default='', help_text='Person/team who implemented', max_length=200),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Specific location', max_length=200),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='machine',
            field=models.CharField(blank=True, default='', help_text='Machine/equipment name', max_length=200),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='mini_factory',
            field=models.CharField(blank=True, default='', help_text='Mini-factory designation', max_length=100),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='month',
            field=models.CharField(blank=True, default='', help_text='Month name (e.g., June, July)', max_length=20),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='prepared_by',
            field=models.CharField(blank=True, default='', help_text='Person who prepared the Kaizen sheet', max_length=200),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='problem_before',
            field=models.TextField(blank=True, default='', help_text='Description of the problem before improvement'),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='suggestion_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the suggestion was made'),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Kaizen improvement title', max_length=500),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='verified_by_name',
            field=models.CharField(blank=True, default='', help_text='Verifier name', max_length=200),
        ),
    ]
