# Generated by Django 5.1.9 on 2026-08-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kaizens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rework', 'Returned for Rework'), ('classified', 'Classification Changed'), ('good_point', 'Marked as Good Point'), ('closed', 'Closed'), ('verified', 'Verified')], max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Reviewer remarks or rejection reason')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('kaizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='kaizens.kaizen')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow History Entry',
                'verbose_name_plural': 'Workflow History',
                'db_table': 'kaizen_workflow_history',
                'ordering': ['-performed_at'],
            },
        ),
    ]
