# Generated by Django 5.1.9 on 2026-08-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kaizens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decided_in_review', models.BooleanField(default=False, help_text='Whether impact review has been conducted')),
                ('reviewed_date', models.DateField(blank=True, null=True)),
                ('overall_closure_status', models.CharField(choices=[('pending_review', 'Pending Review'), ('actions_allocated', 'Actions Allocated'), ('in_progress', 'In Progress'), ('fully_closed', 'Fully Closed')], default='pending_review', max_length=20)),
                ('closure_date', models.DateTimeField(blank=True, null=True)),
                ('closure_remarks', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_closures', to=settings.AUTH_USER_MODEL)),
                ('kaizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_assessment', to='kaizens.kaizen')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_reviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impact Assessment',
                'verbose_name_plural': 'Impact Assessments',
                'db_table': 'kaizen_impact_assessments',
            },
        ),
        migrations.CreateModel(
            name='ImpactAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('man', 'Man'), ('machine', 'Machine'), ('material', 'Material'), ('method', 'Method'), ('measurement', 'Measurement'), ('safety', 'Safety'), ('horizontal_deployment', 'Horizontal Deployment'), ('five_m', '5M Change'), ('pfd', 'PFD Update'), ('pfmea', 'PFMEA Update')], max_length=30)),
                ('description', models.TextField(help_text='Impact action description')),
                ('assigned_owner_name', models.CharField(blank=True, help_text='Display name of the assigned owner', max_length=200)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('not_required', 'Not Required')], default='open', max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('verified_by_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_impact_actions', to=settings.AUTH_USER_MODEL)),
                ('kaizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_actions', to='kaizens.kaizen')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_impact_actions', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='impact.impactassessment')),
            ],
            options={
                'db_table': 'kaizen_impact_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocatedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(help_text='Display name', max_length=200)),
                ('role_description', models.CharField(help_text='e.g., Quality Engineer, Safety Officer', max_length=200)),
                ('task_assigned', models.CharField(help_text='e.g., PFMEA Revision, PFD Drawing', max_length=300)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_to_impacts', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_resources', to='impact.impactassessment')),
            ],
            options={
                'db_table': 'kaizen_resources',
                'ordering': ['employee_name'],
            },
        ),
        migrations.CreateModel(
            name='ImpactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('five_m', '5M Change'), ('safety', 'Safety Impact'), ('pfd', 'PFD Update'), ('pfmea', 'PFMEA Update')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('assigned_to_name', models.CharField(blank=True, help_text='Name of assigned person (for display when user FK not available)', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('not_required', 'Not Required')], default='pending', max_length=20)),
                ('completed_by_name', models.CharField(blank=True, max_length=200)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_items', to='impact.impactassessment')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_impact_items', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_impact_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kaizen_impact_items',
                'ordering': ['category'],
                'unique_together': {('assessment', 'category')},
            },
        ),
    ]
