# Generated by Django 5.1.9 on 2026-08-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kaizens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('kaizen_submitted', 'Kaizen Submitted'), ('kaizen_assigned', 'Assigned for Review'), ('kaizen_approved', 'Kaizen Approved'), ('kaizen_rejected', 'Kaizen Rejected'), ('kaizen_rework', 'Returned for Rework'), ('action_assigned', 'Impact Action Assigned'), ('action_approaching', 'Action Approaching Deadline'), ('action_overdue', 'Action Overdue'), ('verification_required', 'Verification Required'), ('closure_required', 'Closure Required'), ('kaizen_closed', 'Kaizen Closed'), ('voting_opened', 'Voting Opened'), ('voting_closed', 'Voting Completed'), ('general', 'General Notification')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kaizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='kaizens.kaizen')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx')],
            },
        ),
    ]
